# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YouTubeDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YouTubeDemo

  pod 'Kingfisher'
  pod 'YouTubePlayer'
  pod 'ProgressHUD'

  target 'YouTubeDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YouTubeDemoUITests' do
    # Pods for testing
  end

end
